[package]
name = "gluon_check"
version = "0.7.1" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The typechecker for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
env_logger = { version = "0.3.4", optional = true }
log = "0.3.6"
itertools = "0.7.0"
union-find = "0.3.1"
pretty = "0.3.0"
smallvec = "0.2.1"

gluon_base = { path = "../base", version = "0.7.1" } # GLUON
gluon_parser = { path = "../parser", version = "0.7.1", optional = true } # GLUON

[dev-dependencies]
collect-mac = "0.1.0"
pretty_assertions = "0.4"

[features]
test = ["gluon_parser", "env_logger"]

