[package]
name = "gluon_check"
version = "0.9.1" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The typechecker for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
collect-mac = "0.1.0"
log = "0.4"
itertools = "0.7"
union-find = "0.3.1"
pretty = "0.5"
smallvec = "0.6"
rpds = "0.5"
stable_deref_trait = "1"

codespan = "0.1"
codespan-reporting = "0.1"

strsim = "0.8.0"

gluon_base = { path = "../base", version = "0.9.1" } # GLUON
gluon_parser = { path = "../parser", version = "0.9.1", optional = true } # GLUON

[dev-dependencies]
env_logger = "0.5"

gluon_format = { path = "../format", version = "*" }

collect-mac = "0.1.0"
pretty_assertions = "0.5"

[features]
test = ["gluon_parser"]

