[package]
name = "gluon_check"
version = "0.2.2"
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The typechecker for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
env_logger = { version = "0.3.4", optional = true }
log = "0.3.6"
union-find = "0.3.1"
gluon_base = { path = "../base", version = "0.2.2" }
gluon_parser = { path = "../parser", version = "0.2.2", optional = true }

[features]
test = ["gluon_parser", "env_logger"]
