[package]
name = "check"
version = "0.1.0"
authors = ["Markus <marwes91@gmail.com>"]

[dependencies.log]
[dependencies.env_logger]

[dependencies]
union-find = "0.2.2"

[dependencies.mopa]
git = "https://github.com/Marwes/mopa.git"

[dependencies.base]
path = "../base"
[dependencies.parser]
path = "../parser"

