language: rust
sudo: required
services: docker
cache: cargo
matrix:
  include:
  - rust: nightly-2017-12-18
  - rust: beta
  - rust: stable
    env:
      - DEPLOY=1
      - TARGET=x86_64-unknown-linux-gnu
  - rust: nightly-2017-12-18
    env: WASM=1
    # Only for deployment
  - env:
      - TARGET=x86_64-pc-windows-gnu
      - DEPLOY=1
  - env:
      - TARGET=x86_64-apple-darwin
      - DEPLOY=1
    os: osx
os:
- linux

install:
  - sh scripts/install_cross.sh
  - source ~/.cargo/env || true

env:
- RUST_BACKTRACE=1
script:
- >
    if [[ -z ${WASM+set} ]]; then
        ./scripts/travis.sh
    else
        rustup target add wasm32-unknown-unknown
        cargo check --target wasm32-unknown-unknown -p gluon_c-api
    fi

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/78796507a78a48a4b18e
    on_success: change
    on_failure: always
    on_start: never

before_deploy:
- sh scripts/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: ImhF+DkxyHyzDQ4SZZlATjgkrzr+yY1xwADxgO2B5Xi+C7AOllkPInSB/RL+C6tebQnxIEop7KU0N4svbIw6zuoDmOvkliP++U1gXDqvpggBT7AXM5ICcLKWUzTdh3XexhL5SUmtH+QvWRwFwcOoq6mic8rc6DSvTojB/NydyJCeHGvx5iSl5o/ZSqrnEjOF/yDMXADVNwQRZebzyXss+wtTfEbD7OZoJ9ihPugDES8EkmScwS/UCJfCfEqBf/AwDSaAxVpPB/2PF7J0bDIB1ORrwA4HUguJ/U5QuV4vea0hNhhIzzwfcsbPhPLARcLENZLirUk3iygbwSPCTNg+8yEz0MPJQVTj/T48cbKkn9rgZfWi3Bs9nyv22ZouKBFQooiQD6b7WhVGY8bA1Q39cTSLfrR9WrkiRS3x11QrNkwWUqvWHb+2u0KtovTnCt9Lxrx0j8WKMO5Onx6hLfGfH00puCNpV8keWqkzriSi7/ce4mBl8HTvFX22bKZ5uZAxX2mPodAtWoh8hgOGMZhjG2ODS1CEQBxWw5nCXkKQE1afaJOEjhzXmmSNzTnfWIFQGk6V9T9LF8u/PrSVmkQCgka/arlUQlKl+Fa8XUEx8DZEHptj2OdP86A2qiUOcsAmYF2z19kYziHYK3Ll1xDPoOSil6Eej5t+n/e37bmvTMY=
  file_glob: true
  file: gluon-$TRAVIS_TAG-$TARGET.*
  skip_cleanup: true
  on:
    repo: gluon-lang/gluon
    condition: $DEPLOY = 1
