[package]
name = "gluon_doc"
version = "0.9.1" # GLUON
authors = ["Markus Westerlind <marwes91@gmail.com>"]

license = "MIT"

description = "The documentation generator for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
log = "0.4"
env_logger = "0.5"
walkdir = "1"
failure = { version = "0.1", features = ["backtrace"] }
handlebars = "1.0.0-beta.4"
clap = "2.22.0"
itertools = "0.7"
structopt = "0.2"
pretty = "0.5"
pulldown-cmark = "0.1"
regex = "1"
lazy_static = "1"

serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"

gluon = { version = "0.9.1", path = ".." } # GLUON

