[package]
name = "gluon_doc"
version = "0.11.1" # GLUON
authors = ["Markus Westerlind <marwes91@gmail.com>"]
edition = "2018"

license = "MIT"

description = "The documentation generator for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
clap = "2.22.0"
env_logger = "0.6"
failure = { version = "0.1", features = ["backtrace"] }
handlebars = "1.0.0-beta.4"
itertools = "0.8"
lazy_static = "1"
log = "0.4"
opener = "0.3"
pretty = "0.5"
pulldown-cmark = "0.2"
rayon = "1"
regex = "1"
structopt = "0.2"
walkdir = "1"

serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"

gluon = { version = "0.11.1", path = ".." } # GLUON


[dev-dependencies]
#cargo-deadlinks = { path = "../../cargo-deadlinks" }
