[package]
name = "gluon_doc"
version = "0.7.1" # GLUON
authors = ["Markus Westerlind <marwes91@gmail.com>"]

[dependencies]
log = "0.4"
env_logger = "0.5"
walkdir = "1"
failure = { version = "0.1", features = ["backtrace"] }
handlebars = "=1.0.0-beta.1"
clap = "2.22.0"
itertools = "0.7.0"

serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"

gluon = { version = "0.7.1", path = ".." } # GLUON

