[package]
name = "gluon_completion"
version = "0.7.1" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "Auto-completion for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
either = "1.0.0"
itertools = "0.7.0"
walkdir = "2"

gluon_base = { path = "../base", version = "0.7.1" } # GLUON

[dev-dependencies]
collect-mac = "0.1.0"
env_logger = "0.5.0"

gluon_check = { path = "../check", version = "0.7.1" } # GLUON
gluon_parser = { path = "../parser", version = "0.7.1" } # GLUON
